# Generated by Django 2.2.6 on 2019-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.AddField(
            model_name='movie',
            name='dislike',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
