# Generated by Django 2.2.6 on 2019-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislike',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='like',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
