# Generated by Django 2.2.6 on 2019-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191024_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(null=True),
        ),
    ]
