# Generated by Django 2.2.6 on 2019-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191114_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
