# Generated by Django 2.2.6 on 2019-10-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
