# Generated by Django 3.0 on 2021-01-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link_movie',
            field=models.CharField(max_length=200),
        ),
    ]
